//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDeEmpacotamento
{
    using System;
    using System.Collections.Generic;
    
    public partial class log
    {
        public int LOid { get; set; }
        public string LOoperacao { get; set; }
        public System.DateTime LOdata { get; set; }
        public int USid { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
