//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDeEmpacotamento
{
    using System;
    using System.Collections.Generic;
    
    public partial class pacote
    {
        public int PAid { get; set; }
        public string PAtipo { get; set; }
        public int PAquantidade { get; set; }
        public int PAlargura { get; set; }
        public int PAaltura { get; set; }
        public int PAprofundidade { get; set; }
        public int PApeso { get; set; }
        public int MAid { get; set; }
    
        public virtual materiai materiai { get; set; }
    }
}
