//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDeEmpacotamento
{
    using System;
    using System.Collections.Generic;
    
    public partial class produto
    {
        public int PRid { get; set; }
        public string PRnome { get; set; }
        public int PRpeso { get; set; }
        public int PRlargura { get; set; }
        public int PRaltura { get; set; }
        public int PRprofundidade { get; set; }
        public Nullable<int> PRquantidade { get; set; }
    }
}
