//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDeEmpacotamento
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public usuario()
        {
            this.logs = new HashSet<log>();
        }
    
        public int USid { get; set; }
        public string USnome { get; set; }
        public string USlogin { get; set; }
        public string USsenha { get; set; }
        public string Cargo { get; set; }
    
        public virtual ICollection<log> logs { get; set; }
    }
}
